### ISSUE TITLE
A fanciful idea

### ISSUE THREAD

**Issue by kaixinbaba** [WarsWorld/WarsWorld#108]
Is it possible to add single-player content to this project (assuming we train a highly advanced AI, or use open-source methods to train the game's AI)? A customizable campaign mode would be amazing. While playing, I've often fantasized about what it would be like to play as Black Hole in the campaign mode. Custom campaigns could include different levels and victory conditions, which could be shared online. Customizable game content (such as COs, units, and terrain) could also be shared. If all of this were possible, it would be incredibly cool. I'm not entirely satisfied with the single-player content in the latest "NS boot camp" (although I did manage to complete it).

Looking forward to your reply～

**Comment by FemboyDeveloper** [comment]
Albeit having AI and a custom campaign does sound amazing, I think its a bit too far ahead for us to discuss right now since we still dont have an MPV/demo for our closed beta. 

There is also the issue that this will be a website with multiplayer/online features being the centerpiece. Would our project really be the best place for singleplayer only stuff? Think it would be easier to code that into a .exe/its own program so people can easily run it in their PCs while running a website locally would be much harder for the average user.

I'd say give it a good 6-12 months or so, maybe we could make another site thats a clone of this one, focused on singleplayer stuff so maybe people can easily play co-op/see each others campaigns (or maybe even be able to control the enemy).

**Comment by kaixinbaba** [comment]
I'm delighted to receive your reply, and I completely understand the current stage of the project. What makes me even happier is that you haven't outright rejected my fanciful idea. I'm a backend programmer (primarily using Java and Python) and am currently learning the frontend technologies involved in this project (such as Next.js and React). When the time is right, I hope to contribute to the project in my own way. Finally, I want to thank you for starting this project and for making it open source, which allows ordinary people like me who love Advance Wars to participate. **Thank you!**

**Comment by kaixinbaba** [comment]
Gotta, I'm sorry

**Comment by Pauan** [comment]
No problem, it's not a big deal, Discussions are just nicer because they have threads and upvoting and other useful features.
