### ISSUE TITLE
Make map/grid responsive in size

### ISSUE THREAD

**Issue by JaviTrek** [WarsWorld/WarsWorld#4]
### Read different map sizes correctly
Maps in AW have different sizes, some are 18x18, some are 20x20, some 34x26. Our Map needs to be able to take a X column and Y row parameter and render its size correctly depending on the size needed.

### Be able to be increased/decreased in size with something like a +/- button without sacrificing quality/be responsive to screen size
Our grid also needs to be responsive, some people will be playing on their phone, some will be playing on a 4k resolution monitor. Our grid needs to expand adequately for both of these users.

**Comment by leekahung** [comment]
Been messing around with the map grid with SASS while I try to migrate the Layout over from the demo onto my fork.

Managed to make the tiles responsive by using fixed aspect ratios (manually with height and width instead of aspect-ratio) to prevent distortions when the window resizes. Kept gridSize as is. See results below.

https://user-images.githubusercontent.com/14917816/233026255-83960651-ea2c-43a0-9ad4-d910689573bb.mp4

Think it'll be a good step on getting this issue resolved.
