### ISSUE TITLE
Recalculate/think about how we want to store and think about the gamestate data

### ISSUE THREAD

**Issue by JaviTrek** [WarsWorld/WarsWorld#41]
Okay so this one is a reallly big topic that we need to plan out and we cannot just do it without careful planning.

### The issue
How do we store a gameState (the current state of a game/match), we can think about this as chess.

In order for us to be able to save a game state (where units are located, whats their health, whats the players income, etc) we need a notation of sorts, what comes to mind is chess notation.

### What is chess notation?
According to chess.com, Chess notation is the act of recording or writing down the moves of a chess game. Over the years various methods and ways have been used to record the moves, but they have all disappeared except for the current standard for chess notation: algebraic notation.

![Image](https://user-images.githubusercontent.com/96269542/215608139-0d7ad160-ebc1-4aae-b1d4-b2f4e054a34e.png)

![Image](https://user-images.githubusercontent.com/96269542/215608223-7b723b0b-72d5-4a92-80ec-d13e3600212a.png)

You see those letters and numbers? they mean chess pieces, where did they move to and so on. Its a way to save a chess game without having someone go "the white knight moved from A3 to B5 and capture a pawn" but instead "Nxb5" where N means Knight, x means it captured a piece, b5 means where it ended up moving.

## The object option
It is much more human readable and its what was used for AW-Competitive. it worked very well but Im not sure if it will affect performance once we have 100-1000 users. Its basically an array of objects, with array[0] being our first tile and so on.

```
[
//just imagine this is one tile in our Array
   {
      "terrainImage": "bm2",
      "terrainType": "property",
      "terrainOwner": "blueMoon",
      "terrainCapture": 0,
      "tileUnit": {
        "id": 0,
        "name": "Infantry",
        "country": "blueMoon",
        "hp": 100,
        "isUsed": false,
        "capture": false
      }
    }
  ];
```

## The compact string option
 it could also be something tighter than a whole, like just a string with specific parts. So we would have an array of just strings that the frontend can decode/ slice into pieces to understand.

```
[ 'p 00 100 os f' ...];
```
What the heck does this mean? 
p = plains, the terrain its in.
00 = infantry (we'd have unit ID so 00 infantry, 01 mech, 02 recon, etc)
100 = current health status
os = orange star
f = free
(this is an example but its missing a couple of properties)

I'm not sure which one would end up being better or if the difference is even significant enough.The question comes down to whether we want the user's client to decode a compact sequence of letters and numbers or just save/deliver a bigger JSON file thats more human readable. @FunctionDJ also thought about the possibility of just making the JSON more compact for production (kinda like a zip file?) so for now, it seems we will continue to use the object version for a better DX (dev experience)

**Comment by Buluphont** [comment]
Suggestion, or at least food for thought:

I don't think you need to store game state like that. You could instead take a cue from other games (such as your Chess example!), and just store _initial state_ (map, starting units, RNG seed for the game, etc) and the sequence of state-altering _inputs_ for each turn (move unit, attack with unit, produce unit, CO power, end turn, etc). At runtime, the server can just replay all of the inputs in order to reliably reproduce the current game state (or any previous game state). RNG is a concern; for this to work, you need to be able to reproduce game state deterministically. This is why you must save an RNG seed serverside, to be used for the individual game. This increases run-time CPU load, but vastly reduces storage requirements; unlike AWBW, you could probably afford to retain all replays forever, or at least much, much longer than 2 weeks.

So you don't need to _save_ things like current health, money, etc; you just resimulate from the beginning and hold the game in memory for as long as it makes sense to. It's okay to discard the game, because you can just resimulate at relatively low cost anytime.
Relatively low cost... Assuming the average game doesn't go extremely long, and assuming it isn't expensive to simulate turns.

FWIW, this is the approach also used for genres like Fighting Games and (I believe) RTS.

**Comment by FunctionDJ** [comment]
FYI we're *basically* doing chess notation, just less terse.
